### ISSUE TITLE
PreserveNewLines doesn't seem to work

### ISSUE THREAD

**Issue by nicholaswbowen** [Rosey/markdown-draft-js#59] opened 2018-07-10 23:41 UTC
I have PreserveNewLines enabled in the config, but it doesn't seem to be working. 

markdown
```md
foo


bar
```
rich text actual
```
foo
bar
```

rich text expected
```
foo


bar
```

**Comment by Rosey** [comment] 2018-07-12 16:37
Just to confirm, `PreserveNewLines` camel case should be `preserveNewlines` - is it possible you're capitalizing the `L` when it should be lowercase?

**Comment by nicholaswbowen** [comment] 2018-07-12 16:47
just a typo, my bad.  

This is what I am using. 

let foo = markdownToDraft(md, {
    remarkableOptions: {
      preserveNewlines: true,
    },
  });

**Comment by Rosey** [comment] 2018-07-12 16:53
Ah ok if you move the `preserveNewlines` out of remarkableOptions I think it should work 

```js
let foo = markdownToDraft(md, {
  preserveNewlines: true,
});
```

Reason being that it isn't an option that exists in `remarkable`, it's an option explicitly for `markdownToDraft` so it doesn't need to be nested as something to be passed to `remarkable`. I can update the readme to be more clear!

**Comment by Rosey** [comment] 2018-07-24 16:32
just checking in :)

I tested out the demo on the gh-pages branch and added `preserveNewlines: true` and it seemed to work as expected there as well!

**Comment by Rosey** [comment] 2018-08-09 19:35
HMM ok I can recreate after updating to the latest version of markdown-draft-js, sorry! I was running an older version before :(

**Comment by Rosey** [comment] 2018-08-09 19:47
What's interesting and concerning is that there's a test for this and it is passing 😦

**Comment by nicholaswbowen** [comment] 2018-08-14 23:04
This Bug is looking fixed from my end. Thanks!

**Comment by Rosey** [comment] 2018-08-14 23:05
lol what the heck I didn't do anything

**Comment by Rosey** [comment] 2018-08-14 23:05
Maybe it only happens under certain cases

**Comment by igorlesnenko** [comment] 2018-08-15 06:09
DraftJS -> markdown is saved correctly. But when loading from markdown to draft, newlines are collapsed

**Comment by igorlesnenko** [comment] 2018-08-15 09:17
Also, I wonder, why DraftJS:

> first line
> second line

is converted to markdown like:

```
first line

second line
```

Would it be better with preserve lines enabled option to convert to:

```
first line
second line
```

**Comment by igorlesnenko** [comment] 2018-08-15 09:54
Also I think that just blank lines should be escaped like `\`

Otherwise it is difficult to tell for markdown parser if it is blank line within paragraph or the beginning of another paragraph

**Comment by nicholaswbowen** [comment] 2018-08-16 17:03
@Rosey I think I may have figured it out. You need to pass `{ preserveNewlines: true }` into both markdownToDraft and draftToMarkdown. I tried that to troubleshoot and it appeared to fix it.

**Comment by eLysgaard** [comment] 2018-09-18 11:52
@Rosey I just encountered this issue as well. After looking at your sauce I noticed something at the end of the loop in `markdownToDraft`.

```
if (block) {
    previousBlockEndingLine = item.lines[1] + 1;
    blocks.push(block);
}
```
I think the issue stems from adding 1 because then the end of `block` is actually the next line. This makes `totalEmptyParagraphsToCreate` always come out one less than what is should be.

I tried changing it locally directly in my `node_modules` and things seemed to work fine.

**Comment by Rosey** [comment] 2018-09-18 16:44
@eLysgaard Thanks for looking into this! I just quickly tried out your change locally but one of the tests fails with this change so I think there must be more to it than just that 😢 If you're interested in attempting a fix and PR you are welcome to give it a shot though, I'd be very grateful! 

TBH I'm surprised how much interest there is in this feature since markdown doesn't generally preserve new lines, haha.

**Comment by elimisteve** [comment] 2019-02-06 02:11
I am also interested in seeing newlines fully preserved!

@nicholaswbowen Can you please provide a bit more detail? Your solutions sounds great.

**Comment by yekijnuy** [comment] 2019-05-22 21:20
@Rosey Not sure if this is an issue with my code (most likely).  But when I convert `draft` to `markdown` I get the following (example):

`"White↵↵Space"`

Where the return characters were initially line spaces I wanted to include.  I tried to run this when submitting my editorState: 

draftToMarkdown(convertToRaw(contentState), {
        preserveNewlines: true,
      })

Thoughts?

**Comment by Rosey** [comment] 2019-05-22 21:23
and it was stripped despite you not wanting it to be stripped? 🙁 

I kind of want to change the approach with `preserveNewLines` and instead of the logic we currently have, replace it with a `\n&nbsp;` which I think will get-around the default markdown newline escaping and would probably fix most of these bugs. You could probably even do that yourself in the meantime by updating the markdown string you pass in to include a non-breaking space on each newline you want to keep.

Curious what people think of this alternate approach!

**Comment by alexccl** [comment] 2019-07-21 16:19
I put up a PR for this fix.  I think some of the bug reproducibility confusion was caused by the newlines coming after styled vs un-styled blocked.  Everything works as expected when the blocks are not styled, but you will lose a newline on each conversion when a block is styled.

Won't cause an issue during conversion:
```
foo

bar
```

Will cause an issue during conversion:
```
# foo

bar
```

**Comment by Rosey** [comment] 2019-08-03 19:53
Closing since @alexccl 's PR got merged.

**Closed** 2019-08-03 19:52 UTC
Labels: bug, help wanted, high

**Comment by simplenotezy** [comment] 2022-02-24 08:57
> DraftJS -> markdown is saved correctly. But when loading from markdown to draft, newlines are collapsed

hey @Rosey this issue should actually still be open. It's still an issue when going from markdown to draft.

Expected
---
<img width="845" alt="image" src="https://user-images.githubusercontent.com/3786627/155491718-7b2da278-5a79-4ae8-9fb1-6f824ac3e315.png">

Actually happening
---
<img width="841" alt="image" src="https://user-images.githubusercontent.com/3786627/155491783-4b77c2bc-ba8e-4160-a306-1d4419ca93ff.png">
